### ISSUE TITLE
Create a beautiful page for error 404, etc...

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-website#102]
### Is your feature request related to a problem?

if you go to https://archethic.net/ssss, the page is blank with the error

### Describe the solution you'd like

Create a page with the archethic's branding to catch http error

**Comment by manujuniris** [comment]
- [ ] Design a beautiful page 
- [ ] Make changes inside server to display error.html for errors 404, etc

**Comment by redDwarf03** [comment]
Concerning the PR https://github.com/archethic-foundation/archethic-website/pull/108, the design is simple but sufficient.
But, the code is too heavy. it is not necessary to embed the Terms of Use and all js references for example. please clean the html code
