### ISSUE TITLE
Integrate in main page Nodes worldmap emplacement (3D map)

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-website#110]
### Describe the solution you'd like

Following https://github.com/archethic-foundation/archethic-website/issues/96, add a 3-dimensional globe.
Similar to the link below -
https://globe.gl/example/world-cities/

**Comment by redDwarf03** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-website/110?planning-poker) with ZenHub @manujuniris

**Comment by redDwarf03** [comment]
- [ ] : Improve performance
- [ ] : Improve the contrast of the map (or change the map template)
- [ ] : Display geopatch for all nodes

**Comment by manujuniris** [comment]
Pre-production updated with 3d globe
http://54.39.178.165/

**Comment by manujuniris** [comment]
The target for this issue is achieved, this PR would be merged once we have enough Nodes in the network.

**Comment by redDwarf03** [comment]
integrated in the next website
