### ISSUE TITLE
Blog's articles section - Change the data source of the summary

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-website#111]
### Is your feature request related to a problem?

after review with marketing's team, we don't have to use custom excerpt field because this field appears in front of blog article before the image.

### Describe the solution you'd like

So, we should change the field and use meta description

**Comment by redDwarf03** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-website/111?planning-poker) with ZenHub @manujuniris

**Comment by manujuniris** [comment]
For the above issue, please check the following PR - 
https://github.com/archethic-foundation/archethic-website/pull/113
