### ISSUE TITLE
Change geolocally mistake in AE-Web section

### ISSUE THREAD

**Issue by Marc-UCO** [archethic-foundation/archethic-website#126]
### Describe the problem you discovered

On Archethic.net, there is a mistake on the [AE-Web section](https://archethic.net/aeweb.html)
Mistake > Geolocally 

![Screenshot 2022-09-01 at 15 17 00](https://user-images.githubusercontent.com/92734647/187923875-1363879e-0bed-4fd9-8d2a-17f5250541d1.png)

### Describe the solution you'd like

Change geolocally to the correct word

**Comment by redDwarf03** [comment]
"maintainance" is wrong too for info

**Comment by redDwarf03** [comment]
geolocally changes by geographically
