### ISSUE TITLE
Add a new section in website to show our partners

### ISSUE THREAD

**Issue by manujuniris** [archethic-foundation/archethic-website#155]
### Is your feature request related to a problem?

Website requires a new section to display our partners.

### Describe the solution you'd like

Display our association with following partners - 

1. Ennea 
2. Betswirl
3. Professional Genius 
4. Zam.io
5. InvestDex
6. Serenity Shields
7. myeggO

### Additional context

Collect official logos of every partner.

**Comment by redDwarf03** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-website/155?planning-poker) with Zenhub @manujuniris
