### ISSUE TITLE
Link to the bridge

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-website#159]
### Is your feature request related to a problem?

Add a click to action in the top of the website to invite users to go to the bridge to transfer ERC20 UCO to Archethic UCO

### Additional context

url: [bridge.archethic.net](http://bridge.archethic.net/)

**Comment by manujuniris** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/archethic-foundation/archethic-website/159?planning-poker) with Zenhub @redDwarf03
