### ISSUE TITLE
Community's feedbacks

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-website#181]
### Describe the problem you discovered

- [ ] : Size font issue (Page https://www.archethic.net/ecosystem/ on iPhone8, Safari)
![IMAGE 2023-11-12 21:05:54](https://github.com/archethic-foundation/archethic-website/assets/68340133/d15fc9a4-5b58-4c2f-ac3a-4f370951cbcd)

- [x] : Space issue
![IMAGE 2023-11-12 21:08:40](https://github.com/archethic-foundation/archethic-website/assets/68340133/ea75fe2e-7a54-4ff6-9d63-92aefee66b9c)

- [ ] : KPI loading error sometimes
![IMAGE 2023-11-12 21:11:20](https://github.com/archethic-foundation/archethic-website/assets/68340133/e6581dd9-ac9f-4630-9305-74661bd4c766)

- [ ] : Scroll issue (Iphone 13 ios 17.1 wifi) (A partir de la je narrive pas a scroll down meme si le cursor descend 
En plus les trois buttons haut droit je clique dessus rien se passe )
![IMAGE 2023-11-12 21:12:14](https://github.com/archethic-foundation/archethic-website/assets/68340133/ba51f014-21ed-42bf-84b8-a56055b7e634)

- [ ] : Sur le site (avec un iPhone 14 Pro Max) le titre ne s’affiche pas correctement, trop en bas on voit trop l’ADN.

- [ ] : J’ai l’impression que la police d’écriture n’est pas mise à jour sur le wallet.

- [ ] : Les icônes dans les paramètres devraient avoir un padding car elles sont trop collées au bord ça ne fait pas beau non plus.

- [ ] : Sur la landing Page: Cela serait beaucoup plus joli d’enlever le border-bottom du header (le blur suffit pour qu’on ne perde pas l’info des catégories après le scroll).

- [ ] : Le fond du Blog mériterai de s’assombrir pour fusionner parfaitement avec le footer.

- [ ] : D’autre part dans la catégorie du blog, il est fréquent que le cartouche « Join the Community » soit priorisé a l’affichage sur les articles ce qui donne un rendu bizarre.

- [x] : Il faudrait beaucoup plus de padding-top pour le copyright (le passer de 55px à 150px le rendra beaucoup plus beau est pertinent).

- [x] : Dans la page « Developers », à la fin, ça fait bizarre de revoir l’ADN au dessus du footer.

- [ ] : Dans la page « Investisors », ça serait mieux de faire exactement le même style de carousel que dans la page « Developers ».

- [x] : Fin de page pareil que pour la page « Developers » ADN bizarre au dessus du footer.

**Comment by manujvarma** [comment]
1. Size font issue (Page https://www.archethic.net/ecosystem/ on iPhone8, Safari)

2. Scroll issue (Iphone 13 ios 17.1 wifi) (A partir de la je narrive pas a scroll down meme si le cursor descend
En plus les trois buttons haut droit je clique dessus rien se passe )

I'm unable to replicate the above mentioned two issues, it works absolutely fine at my end.

In addition, I have discovered the following issue in the website - 

1. The scrollbar in the carousel section doesn't look aesthetic.

![Screenshot 2023-11-13 134422](https://github.com/archethic-foundation/archethic-website/assets/65886216/44e15847-0d21-45e9-8cd8-cde3637e4b2e)

**Comment by redDwarf03** [comment]
Close this issue because of https://github.com/archethic-foundation/archethic-website/pull/193
