### ISSUE TITLE
Add Team section on the website 

### ISSUE THREAD

**Issue by internet-zero** [archethic-foundation/archethic-website#52]
### Solution

Add the teams sections on archethic.net
- [x] gather all the links, emails, of the team to be displayed on the webpage
- [x] Create a dummy team section
- [ ] Get the photos of all the team members 
- [ ] Tune the team photos to the archethic.net theme
- [ ] Add the team section and add 'Team' in NavBar directing to the team section
- [ ] Team section should be reviewed before publishing

**Comment by I-Archer-Zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-website/52?planning-poker) with ZenHub @samuel-uniris @manujuniris @nilesh-uniris

**Comment by I-Archer-Zero** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-website/52?planning-poker) with ZenHub @I-Archer-Zero

**Comment by redDwarf03** [comment]
following the 13th June marketing meeting, Seb, Nilesh and Christophe will decide the content of this section
