### ISSUE TITLE
AEWeb.html : The screen is shaking

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-website#58]
### What happened?

Hello
it's a very small detail but when the mouse is over the buttons "Deploy on Testnet" and "Install CLI", the text under the button moves.

 

### What is expected ?

I think you should manager the border size of the button in over mode

**Comment by manujuniris** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-website/58?planning-poker) with ZenHub @samuel-uniris @redDwarf03 @internet-zero

**Comment by manujuniris** [comment]
@redDwarf03 
Please review http://54.39.178.165/aeweb.html
The mentioned problem has been fixed.

**Comment by manujuniris** [comment]
> ok for AEWeb. it should be interesting to fix other part of website (archethic.net with buy button or join the community button for example)

Fixed for other parts as well.
Please re-review http://54.39.178.165/

**Comment by redDwarf03** [comment]
ok for me. thx
