### ISSUE TITLE
AE Website's Branding Page => Add a page's menu (on mobile version)

### ISSUE THREAD

**Issue by internet-zero** [archethic-foundation/archethic-website#62]
### Problem to solve - 

The current brand.html page lacks a page menu, especially on the mobile version. On user click the menu should expand and show the relevant content, further when a user clicks on the menu items they should directly navigate to the respective sections inside the page.

**For example -** 

![eth_style](https://user-images.githubusercontent.com/90322956/162366484-1ff8b029-7c37-45d0-8bbc-a5346ab4c3f1.png)

On user click - 

![eth_style](https://user-images.githubusercontent.com/90322956/162367152-e562a207-93cd-4693-b655-b8be2d3f0d60.png)

Brand's page menu content includes- 

1. Logos 
2. Colors
3. Fonts
4. Brand Voice 
5. Brand Story

### Solution -  

The above problem can be solved by implementing the following -

- [x] Create an accordion using CSS 
- [x] Optimize the color of accordion
- [x] Make the accordion clickable
- [x] Using HTML add the menu items
- [x] Navigate to the differents sections of brands page through menu items

**Comment by manujuniris** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-website/62?planning-poker) with ZenHub @internet-zero @nilesh-uniris

**Comment by manujuniris** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-website/62?planning-poker) with ZenHub @samuel-uniris
