### ISSUE TITLE
Improve community section of the archethic.net website

### ISSUE THREAD

**Issue by internet-zero** [archethic-foundation/archethic-website#66]
### Problem to solve

Currently the blog articles connected to the AE Website are not in order and out of date and there are also many sections of the blog articles like tech updates, investors, etc...

### Solution

To make a simple and compact community section with the right blog articles and the right sections

**Comment by manujuniris** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/archethic-foundation/archethic-website/66?planning-poker) with ZenHub @internet-zero
