### ISSUE TITLE
Improve website on the basis of feedback 

### ISSUE THREAD

**Issue by manujuniris** [archethic-foundation/archethic-website#69]
### Problem to solve

Various suggestions have been given by the team to improve different aspects of the website, which will provide a seamless experience to end-users.

### Solution

Improve the following - 
- [x] #72
- [x] #77
- [x] #76
- [x] #71
- [x] #73
- [x] #74
- [x] #75

**Comment by manujuniris** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/archethic-foundation/archethic-website/69?planning-poker) with ZenHub @samuel-uniris @internet-zero

**Comment by redDwarf03** [comment]
This issue will be not fixed in this version of website. The new website includes this point
