### ISSUE TITLE
Improve visibility of Governance section (pie chart) on mobile version

### ISSUE THREAD

**Issue by manujuniris** [archethic-foundation/archethic-website#76]
**Problem -** 

![Screenshot from 2022-06-10 14-20-36](https://user-images.githubusercontent.com/90322956/173028885-b22f223d-8f96-47bb-bbad-6d2d4a004051.png)

The visibility of pie chart in the governance section is not very clear.

**Solution -**

The above problem maybe solved by optimizing the size of pie chart or by trying some better optimization method.

**Comment by redDwarf03** [comment]
This issue will be not fixed in this version of website. The new website includes this point
