### ISSUE TITLE
Explore Fiat On Ramp solution to buy UCO - 

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-website#79]
### Problem to solve

Actually Rubic Widget sends lot of error in javascript and his design and integration are not great.

### Solution

Identity and study other solutions and the integration in website (transak, moonpay). See with Victor

**Comment by redDwarf03** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/archethic-foundation/archethic-website/79?planning-poker) with ZenHub @manujuniris @Neylix @samuel-uniris @internet-zero @nilesh-uniris

**Comment by manujuniris** [comment]
To facilitate the process of buying Archethic (UCO), following are the possible integrations - 

1. Wyre - https://www.sendwyre.com/
2. Xanpool - https://xanpool.com/
3. Transak - https://transak.com/
4. Moonpay - https://www.moonpay.com/
5. Ramp Network - https://ramp.network/

**Comment by manujuniris** [comment]
The link below contains competitive analysis - 

https://lowly-impulse-d88.notion.site/05d1a63c87774cb1ba6a7d1d25ce2dc5?v=055c2f14c779474e9aea47a725064cfa
