### ISSUE TITLE
Brand page : changes

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-website#81]
### What happened?

Could you please : 
- [x] : Change the logo by the last official logo 

### What is expected ?

See what happened section

**Comment by manujuniris** [comment]
@redDwarf03 Changed the logos by the last official logos http://54.39.178.165/brand.html
Please review

**Comment by redDwarf03** [comment]
ok. could you just put on display a height to 118px to be in harmony with other logos please

**Comment by redDwarf03** [comment]
could you reduce the logo like this:
Before
![before](https://user-images.githubusercontent.com/68340133/174545683-58914e43-4d31-437f-adfe-2d3f074005ee.png)

After
![after](https://user-images.githubusercontent.com/68340133/174545701-e8932314-0c98-41a3-b5e0-570cd724f191.png)

**Comment by manujuniris** [comment]
> could you reduce the logo like this: Before ![before](https://user-images.githubusercontent.com/68340133/174545683-58914e43-4d31-437f-adfe-2d3f074005ee.png)
> 
> After ![after](https://user-images.githubusercontent.com/68340133/174545701-e8932314-0c98-41a3-b5e0-570cd724f191.png)

Yes Sure

**Comment by manujuniris** [comment]
Please review http://54.39.178.165/brand.html
