### ISSUE TITLE
Project architecture - structuration and hidden files

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-website#83]
### Problem to solve

Actually the website archethic.net directly pull the files from the main branch. However, there are files that do not have to be served on the website.
For exemple, you can access to archethic.net/README.md or archethic.net/build.js

### Solution

A solution would be to move all files needed by the website into the "dist" folder and let all other files (package.json, build.js, gitignore ...) in the root repository.
And so the archethic.net website will pull the file inside the dist folder and not in the root repository.

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-website/83?planning-poker) with ZenHub @manujuniris @redDwarf03

**Comment by redDwarf03** [comment]
i will see with @seb-uniris to get the access of the server to resolve this issue

**Comment by redDwarf03** [comment]
This issue will be not fixed in this version of website. The new website includes this point
