### ISSUE TITLE
Brand assets page : Changes

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-website#84]
### Is your feature request related to a problem?

no

### Describe the solution you'd like

- [x] : Add logos from https://github.com/archethic-foundation/archethic-assets/tree/main/assets/logos/references_svg except uniris' logos
- [x] : Remove AEWeb logo
- [x] : Reduce the size of color squares in colors section. Put 100x100. 
- [x] : Remove the hexa code from image of color and put the code in text format to help people to copy in clipboard
- [x] : After these updates, check with marketing team the page

**Comment by redDwarf03** [comment]
For White and black logo, i propose:
- Change the title "Archethic White Logo" -> "Archethic White & Black Logo"
- Let the white logo
- Change the button "Download" -> "Download Archethic White Logo"
- Add a button "Download Archethic Black Logo" on the right of the first button with the link to the black logo

**Comment by redDwarf03** [comment]
About Archethic Logo Alone : i'll check with Seb if we share this logo in this color.

**Comment by manujuniris** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/archethic-foundation/archethic-website/84?planning-poker) with ZenHub @internet-zero @redDwarf03

**Comment by manujuniris** [comment]
HI @redDwarf03 

I have done the requested changes, but I'm not very much convinced with the look of brand page, please let me know your views.

Please review the following link - 
 http://54.39.178.165/brand.html

**Comment by redDwarf03** [comment]
perhaps, we could have just for each logo :  
- display the logo with gradient colors
- 3 buttons: download gradient version, download white version, download black version
Could you try this solution ?

**Comment by manujuniris** [comment]
> perhaps, we could have just for each logo :
> 
> * display the logo with gradient colors
> * 3 buttons: download gradient version, download white version, download black version
>   Could you try this solution ?

Yes, I thought of the same solution.
Please re-review the following link - 
http://54.39.178.165/brand.html

**Comment by manujuniris** [comment]
> > perhaps, we could have just for each logo :
> > 
> > * display the logo with gradient colors
> > * 3 buttons: download gradient version, download white version, download black version
> >   Could you try this solution ?
> 
> Yes, I thought of the same solution. Please re-review the following link - http://54.39.178.165/brand.html

Hi @redDwarf03 

Please do the final review :)

**Comment by redDwarf03** [comment]
ok for me. thx
