### ISSUE TITLE
Blog link in footer is not correct

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-website#85]
### Describe the problem you discovered

in the footer of the main page of https://www.archethic.net/, the "blog" link is not correct
Same thing for https://www.archethic.net/lab.html

### Describe the solution you'd like

Please, check all links to blog to verify is links are correct
Change https://uniris.io/blog/tag/media/ with https://blog.archethic.net/

**Comment by manujuniris** [comment]
The problem has been resolved! Please review https://archethic.net

**Comment by redDwarf03** [comment]
ok for me. thx
