### ISSUE TITLE
Define a structure to present different sections of information

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-website#86]
### Describe the solution you'd like

We have to share with users different informations:
- Tech updates
- Partnership
- Global purpose (like Energy Consumption article)

We have to think about segmentation of the website to share these informations that doesn't interest the same population, the same skills and the same importance

Delivery of this issue: Wireframe

### Additional context

Think about the automatisation too like tech update section

**Comment by manujuniris** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/archethic-foundation/archethic-website/86?planning-poker) with ZenHub @internet-zero @redDwarf03

**Comment by manujuniris** [comment]
[Wireframe.pdf](https://github.com/archethic-foundation/archethic-website/files/9055197/Wireframe.pdf)

The above pdf contains a wireframe for the community section.

Please review @redDwarf03 @internet-zero @margarita-uniris @Marc-UCO

**Comment by manujuniris** [comment]
[FInal-Wireframe.pdf](https://github.com/archethic-foundation/archethic-website/files/9069679/FInal-Wireframe.pdf)

The above pdf contain the final wireframe for the community section.

**Comment by manujuniris** [comment]
[FInal_Wireframe.pdf](https://github.com/archethic-foundation/archethic-website/files/9071042/FInal_Wireframe.pdf)

1. Changed order to Global, Tech Updates & Partnership
2. Added "Go to Blog" button
3. Added summary in the latest article and the same can be obtained using the field = custom_excerpt

https://ghost.org/docs/content-api/

![Screenshot from 2022-07-08 15-39-55](https://user-images.githubusercontent.com/90322956/177972165-806e3650-e7ae-4eda-8060-3d72014223ef.png)

**Comment by redDwarf03** [comment]
do you know the difference between ```custom_excerpt```and ```excerpt``` properties ?

**Comment by manujuniris** [comment]
> do you know the difference between `custom_excerpt`and `excerpt` properties ?

Yes 

**custom_excerpt** - is actually what we set whereas **excerpt** - is by default available in every post 

https://ghost.org/docs/themes/helpers/excerpt/

https://ghost.org/changelog/custom-excerpts/

![Screenshot from 2022-07-08 16-52-39](https://user-images.githubusercontent.com/90322956/177983615-c29ae813-ae46-4c76-9b2a-b1bc0d0f7f7c.png)
