### ISSUE TITLE
Archethic Wallet - Add link the youtube playlist dedicated

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-website#88]
### Describe the solution you'd like

- [x] Create Archethic Wallet Youtube Playlist (Rita)
- [x] Add a link to the youtube playlist dedicated to the Archethic Wallet in https://www.archethic.net/lab.html#mobile-wallet

### Additional context

related to https://github.com/archethic-foundation/archethic-website/issues/80 : 
Cancel the point "Remove "watch it" from Mobile Wallet section"

**Comment by redDwarf03** [comment]
Playlist created
https://www.youtube.com/playlist?list=PL6GQEJjcIwHChTok4CJyw3lsmlvoJLnZK

**Comment by manujuniris** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/archethic-foundation/archethic-website/88?planning-poker) with ZenHub @internet-zero @redDwarf03

**Comment by manujuniris** [comment]
> Playlist created https://www.youtube.com/playlist?list=PL6GQEJjcIwHChTok4CJyw3lsmlvoJLnZK

I would like to suggest here the following points to consider -

1. Please add some wallet videos to the Archethic Wallet Playlist on youtube.
2. **Archethic Wallet Section -** we are navigating users to youtube playlist while in **Testnet Faucet Section -** we display a popup to play a video, which is inconsistent.

**Comment by redDwarf03** [comment]
1. Marketing's team will add video tomorrow
2. For me that's not a pb because we have only one video for testnet so you can let the pop up. For archethic wallet, we will have more than one video so the link to playlist is ok

**Comment by manujuniris** [comment]
> 1. Marketing's team will add video tomorrow
> 2. For me that's not a pb because we have only one video for testnet so you can let the pop up. For archethic wallet, we will have more than one video so the link to playlist is ok

Ok then, please do the final review http://54.39.178.165/lab.html
