### ISSUE TITLE
Update "How Archethic scales upto other blockchains?" section

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-website#92]
### Is your feature request related to a problem?

no

### Describe the solution you'd like

- [x] Update the actual table by the first table with 6 blockchains :
https://legendary-octopus-f03.notion.site/comparison-table-ee31b3de6f8b4fd589a13b350d78682d

- [x] Highlight the column "Archethic"

**Comment by manujuniris** [comment]
Hi @redDwarf03 

Comparison table has been updated, please review https://archethic.net/
