### ISSUE TITLE
Mainnet Tasks

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-website#95]
### Describe the solution you'd like

13/07
- [x] : Add banner on the top of the website https://www.archethic.net/ with the correct link to the blog mainnet article
- [x] : Add the banner on the top of the website https://www.archethic.net/lab.html with the correct link to the blog mainnet article
- [x] : https://www.archethic.net/lab.html : Add a button on the left in mainnet section "open mainnet" with https://mainnet.archethic.net/explorer link

14/07 
- [x] : Publish the website in production with issues #89, #84, #88, #85

**Comment by manujuniris** [comment]
Hi @redDwarf03 

Published website with issue #89 #84 #88 #85 

For banner on top please check the following links - 
http://54.39.178.165/
http://54.39.178.165/lab.html

**Comment by manujuniris** [comment]
Hi @redDwarf03 

Can we close this issue?
