### ISSUE TITLE
Integrate in main page Nodes worldmap emplacement

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-website#96]
### Describe the solution you'd like

integrate the map from node explorer in the main screen of archethic.net (just before Developers section) 

Title of the section: Nodes worldmap emplacement
Content from: https://mainnet.archethic.net/explorer/nodes/worldmap

**Comment by manujuniris** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/archethic-foundation/archethic-website/96?planning-poker) with ZenHub @internet-zero @redDwarf03

**Comment by manujuniris** [comment]
- [x] Fetch geo patch using https://mainnet.archethic.net/api/graphiql 

![Screenshot 2022-07-25 175616](https://user-images.githubusercontent.com/90322956/181696297-b82d5762-31e8-453e-9fe9-f169304c6afa.png)

- [x] Use geo patch to fetch latitude and longitude range  

![Screenshot 2022-07-29 062809](https://user-images.githubusercontent.com/90322956/181697818-abeb7dfc-4811-4035-a0ad-7bfb239f4599.png)

- [x] Use echarts to display Map UI using JSON 

![Screenshot 2022-07-29 120744](https://user-images.githubusercontent.com/90322956/181698363-d95561b4-e474-4e5f-a45a-a52a4b8b372b.png)

- [ ] Precisely display/highlight the nodes on the worldmap 

- [ ] Integrate the worldmap on website and adapt to the theme of website

**Comment by manujuniris** [comment]
We have designed a 2-dimensional world map with nodes, in the next issue we have to try implementing the 3-dimensional globe. 
Similar to the link below - 
https://globe.gl/example/world-cities/
